import type { Metadata } from "next";
import "./globals.css";
import React, {Suspense} from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Loading from "./loading";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "ITeach",
  description: "Generated by create next app",
  icons: {
    icon: '/ITeach_logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <header>
        <Navbar/>
      </header>

      <Suspense fallback={<Loading/>}>
          <main>
              {children}
          </main>
      </Suspense>


      <ToastContainer
          position="top-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
      />
      <footer>
        <Footer/>
      </footer>
    </body>
    </html>
  );
}
